language: node_js
node_js:
- "stable"
install: npm install
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - psql -c 'create database fastfoodfast;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
script: npm test
after_success: npm run coverage